### ISSUE TITLE
How to categorize projects that match multiple platforms?

### ISSUE THREAD

**Issue by meichthys** [mattrob33/christian-projects#1]
I love the idea of this project and would like to start contributing some projects. I am however having some difficulty trying to categorize the projects in the categories you have provided. For example if a project works on web desktop and mobile how should that project be categorized under the platforms section?

**Comment by meichthys** [comment]
Would it be easier and more useful to categorize the projects by purpose rather than type and platform? If I was searching for a Christian project, I would probably have a purpose in mind rather than a platform, so perhaps categorizing by purpose might be more useful to users of this list?

**Comment by mattrob33** [comment]
I'm definitely open to rethinking the organization. I'm not a huge fan of it myself, but it's the best I could think of.

Can you explain what you mean by "purpose"? How is that different than "type"? (I will say, at the very least I think "purpose" is a better name than "type" even for the existing category, so if nothing else I would agree we should rename the existing category to "purpose")

**Comment by mattrob33** [comment]
> For example if a project works on web desktop and mobile how should that project be categorized under the platforms section?

In this case the project would be listed three times under "platform", under each of the three categories (web, desktop, and mobile). I mentioned in the ReadMe that some projects may be listed many times. My thought behind that is that people will generally come to this page looking for "mobile projects" or "web projects" or "bible projects" and I would want every relevant project listed under each of those categories, regardless of how many times a given project is actually listed.

**Comment by meichthys** [comment]
> Can you explain what you mean by "purpose"? How is that different than "type"? 

I guess it's mostly semantics, but I guess there's probably not much of a difference between `Type` and `Purpose`
We could do something like [AwesomeSelfHosted](https://github.com/awesome-selfhosted/awesome-selfhosted) and just grow the list of `purpose` or `type` categories as we add more entries. 

> In this case the project would be listed three times under "platform"

Ok, I just wanted to clarify since it would be quite a bit of duplication. Could we perhaps do a table format and have fields in the table that can be checked off to indicate that a project supports the specific platforms? This may help reduce the duplication?
I'm thinking maybe something like the following:

| Project Name | Description         | Language | Web Support? | Desktop Support? | Mobile Support? | Script? | Data? |
|--------------|---------------------|----------|--------------|------------------|-----------------|---------|-------|
| Project 1    | Open source app     | Swift    | ❌            | ❌                | ✅               | ❌       | ❌     |
| Project 2    | Open source website | HTML     | ✅            | ✅                | ❌               | ❌       | ❌     |
| Project 2    | Open source scripts | Python   | ❌            | ❌                | ❌               | ✅       | ❌     |
| Project 4    | Open source hymns   | English  | ✅            | ✅                | ✅               | ❌       | ✅     |

**Comment by mattrob33** [comment]
Hmm possibly. This would definitely help reduce duplication. I also like that this lets us add "language" as a category, since that was another field I initially wanted but it doesn't work well within the current structure. Three difficulties I see with this approach though are

1. It makes it _slightly_ more difficult to, e.g., "find all mobile apps" (especially if we have 100+ projects)
2. It makes it _much_ more difficult to, e.g., "find all Greek New Testament projects"
3. It starts to become unwieldy as we need more categories (what if we wanted to add "watch" as a platform, or separate Mobile into Android and iOS?)

Any thoughts on those? I definitely like certain strengths of this approach and am very open to it if we can mitigate those difficulties or if we decide they are simply worth dealing with.

**Comment by meichthys** [comment]
1. Yes, this was my concern too. I specifically install a firefox plugin called [sortable](https://addons.mozilla.org/en-US/firefox/addon/sortable/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) just for this purpose. It allows you to sort any html table. It probably wouldn't be great for us to expect users to install an extension just to be able to sort though. If only github markdown tables were sortable!
2. Couldn't you just search for "Greek" as the Language?
3. Agreed. Too many fields will probably result in mostly ❌'s. We would probably need to add fields sparingly. Perhaps we can have a field called "Supported Platforms" and just add text to the field indicating each supported platform. The advantage of this approach would be that we could link directly to the download application or source for each platform:

Project Name | Description | Language | Suported Platforms
-- | -- | -- | -- 
Project 1 | Open source app | Swift | ios, android
Project 2 | Open source website | HTML | web
Project 2 | Open source scripts | Python | windows, linux
Project 4 | Open source hymns | English | [web](http://openhymnal.org/)

**Comment by mattrob33** [comment]
Sortable is a cool extension, I hadn't seen that before.

If only Github supported sortable tables... My original thought was actually to make this a web app with search/sort/filter functionality, but thankfully I was talked out of it :) I would love to also be able to include fields like `framework` that would allow you to, say, find only Django projects or Nest.js projects or Flutter projects.

In your updated suggestion we could easily add a field for that. At that point it becomes less "user-friendly" in that a user can't just scroll down to the Android apps section, for example, but more flexible in that you can quickly search for "android" or "flutter" or whatever.

I'm leaning toward this at the moment I think... Although I don't like overloading the meaning of "language" to mean "programming language" or "natural human language." For example, I have a Greek New Testament app written in Kotlin. The "language" there should be "Kotlin" not "Greek."

Thoughts?

**Comment by meichthys** [comment]
Thanks, i see what you mean about overloading the "language" field, and agree that it wouldn't be good to overload it. If a project is written in a language, the programming language should be listed.  I didn't realize that you were referencing a software project. I thought you were talking about some kind of translation instead.

Do you think having "Greek" in the project name/description would be enough for your scenario? Most projects probably won't have a natural human language, so I'm not sure if it warrants a separate field?

**Comment by mattrob33** [comment]
Yeah I don't think natural language warrants a separate field. I think having "Greek" in the project description would be good enough in that scenario, since you could just search for "greek." It does pose some complications though since it essentially makes project properties dynamically typed rather than statically typed, to use a coding illustration.

So "Greek" works fine if the project description is "Greek New Testament Reader" but what if it is "Original language Bible texts" to indicate that it is both Greek and Hebrew? Then ironically it won't show up in a search for either "Greek" or "Hebrew." And you could have the same problem with things like "creeds" or "confessions" vs "church documents" - it's a lot less deterministic.

We could offset that to some extent by being careful about the wording when reviewing PRs, but it's sort of an inherent difficulty with this approach. It still may be worth doing - I'm just trying to think through the possibilities ahead of time.

**Comment by mattrob33** [comment]
Maybe to start with the tabular approach you suggested (probably the second one?) is the way to go, and if it grows out of hand then it might be time to change approaches or even consider a filterable web app approach.

**Comment by mattrob33** [comment]
Another option I suppose to mitigate that difficulty would be to add a "statically-typed" field to indicate the project type. So, for example, "Original languages" can be a project type that users can safely search for and know they are hitting all relevant results because the moderators have ensured that's the case, regardless of whether the project description happens to contain that word.

**Comment by mattrob33** [comment]
Project Name | Description | Type | Language | Suported Platforms
-- | -- | -- | -- | --
Project 1 | Open source app | English Bible | Swift | ios, android
Project 2 | Open source website | Prayer/Meditation | HTML | web
Project 3 | Open source scripts | Original Languages | Python | windows, linux
Project 4 | Open source hymns | Hymns | English | web

**Comment by mattrob33** [comment]
Yeah the awesome-list model is what I was originally wanting to follow, but I was trying to make it easier for different types of users. I imagine two general types of users, one looking for a project of a specific purpose, regardless of platform, and the other looking for any projects for a specific platform. So for example,

1. A junior iOS developer wanting to find Christian iOS app projects to contribute to.
2. A web dev wanting to build a Greek New Testament web app and looking for _any_ OSS GNT projects that might contain data to use as a starting point.

A third potential type would be someone looking for any Django projects or Flutter projects to contribute to, which is why I was wanting to add a `framework` field.

**Comment by meichthys** [comment]
I like the thinking for sure - both for developers and users.

I do still like the table method, but I also see the benefits of the bulleted list method when it comes to grouping projects into categories.  Perhaps we could do both? What if we had a separate table for each category, that way we could still have a table of contents that can link to each table and we can still keep our fields. It might not be ideal for  developers, but i think that group of people would be more likely to use ctrl-f to find what they want. 

What do you think about this hybrid approach?

**Comment by mattrob33** [comment]
I like that idea best so far I think.

Also just to clarify purpose, this is only intended for developers, non everyday users. So for example I work on the ESV Android app for Crossway. That app would not be allowed in this list since it's not open source and doesn't serve developers in any technical way. But the ESV API would be allowed on the list because it offers an API service that can be used free-of-charge for qualifying projects.

**Comment by mattrob33** [comment]
This has been really helpful by the way, thanks for your early contributions!

**Comment by danbenn** [comment]
I like the "supported platforms" option!

**Comment by meichthys** [comment]
Do you intend this to only be for Bible type projects? How about software products related to church presentation or church management or the like?

**Comment by mattrob33** [comment]
Church presentation software would absolutely qualify! Just as long as the projects are open source or provide a free API/service that other developers could use for building their own projects.

**Comment by meichthys** [comment]
I'll close this issue now that we've settled on a format 👍
